### ISSUE TITLE
Get transponder data from SatNOGS database

### ISSUE THREAD

**Issue by oyvkar** [la1k/flyby#49]
The DIY open ground station network SatNOGS has a database module that contains transponder-information that can be found [here](https://db.satnogs.org/).

The transponder database is based on user-inputs and contains uplink and downlink information in a reasonable format. It also indicates if the satellite is alive or not.

The database has an API which can be found [here](https://db.satnogs.org/api/).

Flyby should ship with a tool similar to update-tle that fetches data from db.satnogs.org to generate a transponder database.

**Comment by bjorgan** [comment]
Probable steps in bash-script:

1. Fetch transponder information from all satellites (should not be necessary to limit the satellites to satellites in TLE database since there are not that many, but in that case we would need flyby CLI functionality for listing all NORAD ids in TLE database and fetch transponders based on the IDs)
2. Generate flatfile transponder database as expected by predict/flyby (see default/flyby.db for template) to temporary file.

Flyby should probably also define some new CLI options for merging in the generated file with the transponder database the user already has saved in his local directory, so that we don't overwrite user-defined information.
