### ISSUE TITLE
Missing ~/.config directory leads to segmentation fault 

### ISSUE THREAD

**Issue by bostrt** [la1k/flyby#73]
I'm running flyby on a minimal raspberry pi installation. The `pi` user does not have the home user's xdg paths (like .config/) setup and entering the initial QTH information into flyby results in a segfault b/c `fd` == 0x0 here: https://github.com/la1k/flyby/blob/master/src/qth_config.c#L60-L62

**Comment by bostrt** [comment]
Running `xdg-user-dirs-update` automatically creates the required `.config/` directory and flyby works fine.

**Comment by bjorgan** [comment]
Thanks for the issue! And also thanks for tracking the source of the error and submitting a PR. It'll solve the error when `XDG_CONFIG_HOME` and `XDG_DATA_HOME` are empty or set to the assumed defaults, which accounts for most of the cases. I've merged the PR.

However, the same problem could be triggered if they are set to anything else (e.g. `export XDG_CONFIG_HOME=/tmp/unlikely/chain/of/directories`, or set `HOME` to something arbitrary). I'll keep this issue open until I've dealt with that. Might just end up exiting with error in order to avoid having to drag in a full recursive version of `mkdir`. It does in any case make sense to explicitly create the defaults if required.

**Comment by bjorgan** [comment]
Ended up doing a full recursion anyway, fixed in 6518de65f480b886382a19064336f4714f7fd9d1.
